### ISSUE TITLE
Fail with gulp@5

### ISSUE THREAD

**Issue by firefoxic** [khalyomede/gulp-sharp-responsive#19]
After upgrading gulp to version 5, everything in the project works except this plugin. For some reason, `image-size` stops recognizing the file type.

```
TypeError: unsupported file type: undefined (file: undefined)
    at lookup (/home/firefoxic/Projects/test/node_modules/image-size/dist/index.js:43:11)
    at Object.imageSize [as default] (/home/firefoxic/Projects/test/node_modules/image-size/dist/index.js:99:16)
    at _loop_1 (/home/firefoxic/Projects/test/node_modules/gulp-sharp-responsive/lib/index.js:98:61)
    at Transform._transform (/home/firefoxic/Projects/test/node_modules/gulp-sharp-responsive/lib/index.js:143:13)
    at Transform._read (/home/firefoxic/Projects/test/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:166:10)
    at Transform._write (/home/firefoxic/Projects/test/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:155:83)
    at doWrite (/home/firefoxic/Projects/test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:390:139)
    at writeOrBuffer (/home/firefoxic/Projects/test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:381:5)
    at Writable.write (/home/firefoxic/Projects/test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:11)
    at ReadableState.drain (/home/firefoxic/Projects/test/node_modules/streamx/index.js:343:47)
```

**Comment by khalyomede** [comment]
Hi, thank you for reporting the issue. I'll check to add support for gulp 5. No ETA (I'll try to check during the weekend).
